name: Auto Pull Request

on:
    create:
        branches:
            - '*' # triggers for any new branch

jobs:
    create-auto-pull-request:
        # skips for branches starting with no auto pr
        if: "!startsWith(github.ref_name, 'no_auto_pr_')"
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Get commit messages
                id: get_commits
                run: |
                    # Get commits since last PR or base branch
                    COMMITS="$(git log origin/main..HEAD --pretty=format:"- %s (%h)" --reverse)"
                    echo "commits<<EOF" >> $GITHUB_OUTPUT
                    echo "$COMMITS" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT


            # Create Pull Request
            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v5
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    assignee: ${{ github.actor }}
                    title: ${{ github.ref_name }}
                    body: |
                        ## Changes
                            This PR includes the following commits:
                            ${{ steps.get_commits.outputs.commits }}
                            ---
                            Auto-generated by GitHub Actions
                    branch: ${{ github.ref_name }}
                    base: main
