name: Pull Request Checks

on:
    #pull_request:
    push:
        branches:
            - main
            - ci_coverage

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    checks:
        runs-on: ubuntu-latest
        timeout-minutes: 25
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: gradle

            - name: Setup Android Sdk
              uses: android-actions/setup-android@v3

            - name: Accept Android Sdk Licenses
              run: yes | sdkmanager --licenses

            - name: Setup emulator system image
              run: |
                sdkmanager "system-images;android-33;google_apis;x86_64"
                echo "$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

            - name: Make gradlew executable
              run: chmod +x ./gradlew

#            - name: Cache Gradle
#              uses: actions/cache@v3
#              with:
#                # Directories to cache
#                path: |
#                    ~/.gradle/caches
#                    ~/.gradle/wrapper
#                # Key must change when Gradle files change
#                key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
#                restore-keys: |
#                    gradle-${{ runner.os }}-

#            - name: Cache Maven
#              uses: actions/cache@v3
#              with:
#                path: ~/.m2/repository
#                key: maven-${{ runner.os }}-${{ hashFiles('**/build.gradle*') }}
#                restore-keys: |
#                    maven-${{ runner.os }}-

#            - name: Cache Android SDK
#              uses: actions/cache@v3
#              with:
#                path: ~/.android
#                key: android-sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle*') }}
            - name: Enable KVM
              run: |
                echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                sudo udevadm control --reload-rules
                sudo udevadm trigger --name-match=kvm

            - name: Run connected tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 33
                arch: x86_64
                target: google_apis
                profile: pixel_6
                ram-size: 2048M
                heap-size: 512M
                disable-animations: true
                emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                script: ./gradlew jacocoAndroidTestReport

#            - name: Connected Android Test
#              run: |
#                  ./gradlew connectedAndroidTest

#            - name: Lint with Ktlint
#              run: |
#                ./gradlew ktlintCheck
#
#            - name: Lint with detekt
#              run: |
#                  ./gradlew detekt

#            - name: Run Android Coverage Report
#              run: |
#                  ./gradlew startTestEmulator jacocoAndroidTestReport

            - name: Debug CI file structure
              run: |
                    pwd
                    ls -la build/reports/jacoco

            - name: Upload Coverage Report
              uses: actions/upload-artifact@v4
              with:
                  name: android-coverage-report
                  path: |
                      build/reports/jacoco/jacocoAndroidTestReport/**

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  files: build/reports/jacoco/jacocoAndroidTestReport/jacocoAndroidTestReport.xml
