name: Auto Pull Request

on:
    push:
        branches:
            - 'auto_pr'
    create:
        branches:
            - '*' # triggers for any new branch

jobs:
    create-auto-pull-request:
        # skips for branches starting with no auto pr
        #if: "!startsWith(github.ref_name, 'no_auto_pr_')"
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            -   name: Checkout repository
                uses: actions/checkout@v6

#            -   name: Get commit messages
#                id: get_commits
#                run: |
#                    git fetch --all
#                    # Get commits since last PR or base branch
#                    COMMITS="$(git log origin/main..HEAD -- --pretty=format:"- %s (%h)" --reverse)"
#                    echo "commits<<EOF" >> $GITHUB_OUTPUT
#                    echo "$COMMITS" >> $GITHUB_OUTPUT
#                    echo "EOF" >> $GITHUB_OUTPUT

            # Create Pull Request
            -   name: Create Pull Request
                id: cpr
                uses: peter-evans/create-pull-request@v8
                with:
                    base: main
                    token: ${{ secrets.PUSH_TO_GITHUB_TOKEN }}
                    author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
                    assignees: ${{ github.actor }}
                    commit-message: Update report
                    title: ${{ github.ref_name }}
                    body: "Test PR"
                    branch: ${{ github.ref_name }}
                    draft: false
